# set random seed, so that you may reproduce your result.
__set_seed1: !apply:random.seed [1986]
__set_seed2: !apply:numpy.random.seed [1986]
__set_seed3: !apply:torch.manual_seed [1986]
__set_seed4: !apply:torch.cuda.manual_seed_all [1986]

dtype: 'bf16'
use_embedding: True    # 自回归模块是否使用embedding

# fixed params
codec_type: "s3tokenizer_v2"
sample_rate: 24000
llm_input_size: 896
llm_output_size: 896
text_encoder_input_size: 512
spk_embed_dim: 512
qwen_pretrain_path: "../../../pretrained_models/CosyVoice2-0.5B/CosyVoice-BlankEN"
# second of min length, if the duration of a audio is less than this, it will be duplicated.
# for speaker audio crop, 0 means do not crop
spk_audio_crop: 10

s3tokenizer_ckpt: "../../../pretrained_models/s3tokenizer"
speaker_encoder_ckpt: "../../../pretrained_models/speaker_encoder_v2.pt"
use_pause_label: True  # whether use human labeled or MFA aligned pause labels

# model params
# for all class/function included in this repo, we use !<name> or !<new> for intialization, so that user may find all corresponding class/function according to one single yaml.
# for system/third_party class/function, we do not require this.
llm: !new:cosyvoice.llm.llm.Qwen2LM
    llm_input_size: !ref <llm_input_size>
    llm_output_size: !ref <llm_output_size>
    speech_token_size: 6561
    length_normalized_loss: True
    lsm_weight: 0
    mix_ratio: [5, 15]
    use_embedding: !ref <use_embedding>
    spk_embed_dim: !ref <spk_embed_dim>
    llm: !new:cosyvoice.llm.llm.Qwen2Encoder
        pretrain_path: !ref <qwen_pretrain_path>
    sampling: !name:cosyvoice.utils.common.non_random_ras_sampling
        top_p: 0.8
        top_k: 10
        win_size: 10
        tau_r: 0.1
        expand_scale: 2

flow: !new:cosyvoice.flow.flow.CausalMaskedDiffWithXvec
    input_size: 512
    output_size: 80
    spk_embed_dim: !ref <spk_embed_dim>
    output_type: 'mel'
    vocab_size: 6561
    input_frame_rate: 25
    only_mask_loss: True
    token_mel_ratio: 2
    pre_lookahead_len: 3
    encoder: !new:cosyvoice.transformer.upsample_encoder.UpsampleConformerEncoder
        output_size: 512
        attention_heads: 8
        linear_units: 2048
        num_blocks: 6
        dropout_rate: 0.1
        positional_dropout_rate: 0.1
        attention_dropout_rate: 0.1
        normalize_before: True
        input_layer: 'linear'
        pos_enc_layer_type: 'rel_pos_espnet'
        selfattention_layer_type: 'rel_selfattn'
        input_size: 512
        use_cnn_module: False
        macaron_style: False
    decoder: !new:cosyvoice.flow.flow_matching.CausalConditionalCFM
        in_channels: 240
        n_spks: 1
        spk_emb_dim: 80
        cfm_params: !new:omegaconf.DictConfig
            content:
                sigma_min: 1e-06
                solver: 'euler'
                t_scheduler: 'cosine'
                training_cfg_rate: 0.2
                inference_cfg_rate: 0.7
                reg_loss_type: 'l1'
        estimator: !new:cosyvoice.flow.decoder.ConditionalDecoder
            in_channels: 320
            out_channels: 80
            causal: True
            channels: [256]
            dropout: 0.0
            attention_head_dim: 64
            n_blocks: 4
            num_mid_blocks: 12
            num_heads: 8
            act_fn: 'gelu'

hift: !new:cosyvoice.hifigan.generator.HiFTGenerator
    in_channels: 80
    base_channels: 512
    nb_harmonics: 8
    sampling_rate: !ref <sample_rate>
    nsf_alpha: 0.1
    nsf_sigma: 0.003
    nsf_voiced_threshold: 10
    upsample_rates: [8, 5, 3]
    upsample_kernel_sizes: [16, 11, 7]
    istft_params:
        n_fft: 16
        hop_len: 4
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    source_resblock_kernel_sizes: [7, 7, 11]
    source_resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    lrelu_slope: 0.1
    audio_limit: 0.99
    f0_predictor: !new:cosyvoice.hifigan.f0_predictor.ConvRNNF0Predictor
        num_class: 1
        in_channels: 80
        cond_channels: 512

# processor functions
eng_frontend: !name:cosyvoice.tokenizer.phoneme_tokenizer.get_eng_frontend
detect_language: !name:cosyvoice.tokenizer.phoneme_tokenizer.detect_language
mix_text_pinyin: !name:cosyvoice.dataset.processor_kaldidata.mix_text_pinyin
    eng_frontend: !ref <eng_frontend>
    detect_language: !ref <detect_language>
get_tokenizer: !name:cosyvoice.tokenizer.tokenizer.get_qwen_tokenizer
    token_path: !ref <qwen_pretrain_path>
    skip_special_tokens: True
allowed_special: 'all'
tokenize: !name:cosyvoice.dataset.processor_kaldidata.tokenize
    get_tokenizer: !ref <get_tokenizer>
    allowed_special: !ref <allowed_special>
filter: !name:cosyvoice.dataset.processor_kaldidata.filter
    max_length: 4000  # 100 frame per second
    min_length: 0
    token_max_length: 512    # phoneme length
    token_min_length: 1
resample: !name:cosyvoice.dataset.processor_kaldidata.resample
    resample_rate: !ref <sample_rate>
feat_extractor: !name:cosyvoice.dataset.processor_kaldidata.mel_spectrogram
    n_fft: 1920
    num_mels: 80
    sampling_rate: !ref <sample_rate>
    hop_size: 480
    win_size: 1920
    fmin: 0
    fmax: 8000
    center: False
compute_fbank: !name:cosyvoice.dataset.processor_kaldidata.compute_fbank
    feat_extractor: !ref <feat_extractor>
shuffle: !name:cosyvoice.dataset.processor_kaldidata.shuffle
    shuffle_size: 1000
sort: !name:cosyvoice.dataset.processor_kaldidata.sort
    sort_size: 500  # sort_size should be less than shuffle_size
batch: !name:cosyvoice.dataset.processor_kaldidata.batch
    batch_type: 'static'
    batch_size: 8
    max_frames_in_batch: 20000   # 100 frame per second
padding: !name:cosyvoice.dataset.processor_kaldidata.padding
    use_spk_embedding: False # change to True during sft
truncate: !name:cosyvoice.dataset.processor_kaldidata.truncate
    truncate_length: 360000  # 24k, 15second for inference
get_transcriber: !name:cosyvoice.dataset.transcriber.get_transcriber
transcribe: !name:cosyvoice.dataset.processor_kaldidata.transcribe
    get_transcriber: !ref <get_transcriber>
add_emo_token: !name:cosyvoice.dataset.processor_kaldidata.add_emo_token
# dataset processor pipeline
data_pipeline: [
    !ref <add_emo_token>,   # 先在文本上加上emotion_token
    !ref <mix_text_pinyin>,
    !ref <tokenize>,
    !ref <filter>,
    !ref <resample>,
    !ref <compute_fbank>,
    !ref <shuffle>,
    !ref <sort>,
    !ref <batch>,
    !ref <padding>,
]

infer_data_pipeline: [
    !ref <filter>,
    !ref <resample>,
    !ref <tokenize>,
    !ref <compute_fbank>,
    !ref <batch>,
    !ref <padding>,
]

# train conf
train_conf:
    optim: adam
    optim_conf:
        lr: 0.001  # change to 1e-5 during sft
    scheduler: warmuplr # warmuplr # change to constantlr during sft
    scheduler_conf:
        warmup_steps: 2500
    max_epoch: 200
    grad_clip: 5
    accum_grad: 2
    log_interval: 100
    save_per_step: 10000

# multiple train data dir
train_data: [
    # 0
    [ "/data/megastore/SHARE/TTS/VoiceClone/NTTS/NTTS" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ENTTS/ENTTS" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/LTTS/LTTS" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/MSTTS_EN/MSTTS_EN" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/MSTTS_CN/MSTTS_CN" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ENTTS_LibriTTS/ENTTS_LibriTTS" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/Live_LuoYonghao/Live_LuoYonghao" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/TTS_unlab/TTS_unlab" ],
    # 8
    [ "/data/megastore/SHARE/TTS/VoiceClone/ASR_KeSpeech/ASR_KeSpeech" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ASR_WenetSpeech/ASR_WenetSpeech" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/Mandarin/Mandarin" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ASR_CN5k/ASR_CN5k" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ManEngMix/ManEngMix" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ASR_MLS/ASR_MLS" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/Conversation/Conversation" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ASR_LibriHeavy/ASR_LibriHeavy" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ASR_Refine/ASR_Refine" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone/ASR_GigaSpeech/ASR_GigaSpeech" ],
    # 18
    [ "/data/megastore/SHARE/TTS/VoiceClone2/20240122/20240122" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240129/20240129" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240205/20240205" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240205_1/20240205_1" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240212/20240212" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240212_1/20240212_1" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240219/20240219" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240226/20240226" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240304/20240304" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240304_en/20240304_en" ],
    # 28
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality1/HighQuality1" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality1_en/HighQuality1_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality2/HighQuality2" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality3_en/HighQuality3_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality4/HighQuality4" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality4_en/HighQuality4_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality5/HighQuality5" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality5_en/HighQuality5_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality6/HighQuality6" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality6_en/HighQuality6_en" ],
    # 38
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality7/HighQuality7" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality7_en/HighQuality7_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality8/HighQuality8" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality8_en/HighQuality8_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality9/HighQuality9" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality9_en/HighQuality9_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality10/HighQuality10" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality10_en/HighQuality10_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality11/HighQuality11" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/HighQuality11_en/HighQuality11_en" ],
    # 48
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240311/20240311" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240311_en/20240311_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240318/20240318" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240318_en/20240318_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240930/20240930" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20240930_en/20240930_en" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20241007/20241007" ],
    [ "/mnt/nas/Datasets/Audio/TTS/VoiceClone2/20241007_en/20241007_en" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/20241014/20241014" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/20241014_en/20241014_en" ],
    # 58
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality12/HighQuality12" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality12_en/HighQuality12_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality13/HighQuality13" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality13_en/HighQuality13_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality14/HighQuality14" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality14_en/HighQuality14_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality15/HighQuality15" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/HighQuality15_en/HighQuality15_en" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/HighQuality16/HighQuality16" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/HighQuality16_en/HighQuality16_en" ],
    # 68
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/MidQuality1/MidQuality1" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone/MidQuality1_en/MidQuality1_en" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/20241021/20241021" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone2/20241021_en/20241021_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241028/20241028" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241028_en/20241028_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241104/20241104" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241104_en/20241104_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241111/20241111" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241111_en/20241111_en" ],
    # 78
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241118/20241118" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241118_en/20241118_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241125/20241125" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/20241125_en/20241125_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality17/HighQuality17" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality17_en/HighQuality17_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality18/HighQuality18" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality18_en/HighQuality18_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality19/HighQuality19" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality19_en/HighQuality19_en" ],
    # 88
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality20/HighQuality20" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality20_en/HighQuality20_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality21/HighQuality21" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality21_en/HighQuality21_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22/HighQuality22" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22_en/HighQuality22_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22_1/HighQuality22_1" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality22_1_en/HighQuality22_1_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality23/HighQuality23" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality23_en/HighQuality23_en" ],
    # 98
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality24/HighQuality24" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality24_en/HighQuality24_en" ],
    # 100
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality25/HighQuality25" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality25_en/HighQuality25_en" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality26/HighQuality26" ],
    [ "/mnt/nas/Datasets2/Audio/TTS/VoiceClone2/HighQuality26_en/HighQuality26_en" ],

    # 104
    [ "/data/megastore/SHARE/TTS/VoiceClone3/DongwuZQ/DongwuZQ" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/DuXY_ManM/DuXY_ManM" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_Musk/ENTTS_Musk" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_Scarlett/ENTTS_Scarlett" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_VC/ENTTS_VC" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_VC1/ENTTS_VC1" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_VC2/ENTTS_VC2" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_VC3/ENTTS_VC3" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_VC4/ENTTS_VC4" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_VC5/ENTTS_VC5" ],
    #114
    [ "/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_VC6/ENTTS_VC6" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/Foreign_IP/Foreign_IP" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/GuangdongTiyu/GuangdongTiyu" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_chn/IP_chn" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_chn2/IP_chn2" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_chn3/IP_chn3" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_chn4/IP_chn4" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_chn5/IP_chn5" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_chn6/IP_chn6" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_chn7/IP_chn7" ],
    #124
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_eng/IP_eng" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_eng2/IP_eng2" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/IP_eng3/IP_eng3" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/MengNiu/MengNiu" ],
    [ "/data/megastore/SHARE/TTS/VoiceClone3/XmovLJ/XmovLJ" ],

    #  中英混
    ["/data/megastore/SHARE/TTS/VoiceClone3/IP_cnenmix/IP_cnenmix" ],
    # 多情感
    ["/data/megastore/SHARE/TTS/MultiEmotion/Batch1/Batch1" ],
    #131
]

train_data_indexes: [
    [0,1,2,3,4,5,
     104,105,
     106,107,108,109,110,
     111,112,113,114,115,
     116,117,118,119,120,
     121,122,123,124,125,
     126,127,128,129,130
    ]
]

train_data_indexes1: [
    # [0,1,2,3,4,5],
    [6,7], [8,9], [10,11], [12,13], [14,15],
    [16,17], [18,19], [20,21], [22,23], [24,25],
    [26,27], [28,29], [30,31], [32,33], [34,35],
    [36,37], [38,39], [40,41], [42,43], [44,45],
    [46,47], [48,49], [50,51], [52,53], [54,55],
    [56,57], [58,59], [60,61], [62,63], [64,65],
    [66,67], [68,69], [70,71], [72,73], [74,75],
    [76,77], [78,79], [80,81], [82,83], [84,85],
    [86,87], [88,89], [90,91], [92,93], [94,95],
    [96,97], [98,99], [100,101], [102,103],
]

cv_data: [
    ["/data/megastore/SHARE/TTS/VoiceClone3/DongwuZQ/DongwuZQ"],
    ["/data/megastore/SHARE/TTS/VoiceClone3/XmovLJ/XmovLJ"],
    ["/data/megastore/SHARE/TTS/VoiceClone3/MengNiu/MengNiu"],
    ["/data/megastore/SHARE/TTS/VoiceClone3/GuangdongTiyu/GuangdongTiyu"],
    ["/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_Musk/ENTTS_Musk"],
    ["/data/megastore/SHARE/TTS/VoiceClone3/ENTTS_Scarlett/ENTTS_Scarlett"],
]